

- name: configure /etc/hosts on the host
  template: src=hosts.j2 dest=/etc/hosts


- name: configure lo:0
  template: src=loopback.j2 dest=/etc/sysconfig/ifcfg-lo:0

- name: configure uplink1
  template: src=uplink1.j2 dest=/etc/sysconfig/ifcfg-uplink1

- name: configure lo:0
  template: src=uplink2.j2 dest=/etc/sysconfig/ifcfg-uplink2
