
# Install required packages
- name: get the mitaka packages
  yum: pkg=centos-release-openstack-mitaka state=present update_cache=yes

- name: install packages
  yum: pkg={{item}} state=present update_cache=yes
  with_items:
    - openstack-neutron-linuxbridge
    - ebtables
    - ipset
    - python-openstackclient



- name: neutron config files
  template: src={{item}}.j2 dest=/etc/neutron/{{item}}
  with_items:
      - neutron.conf
  notify: restart neutron

- name: ml2 config files
  template: src={{item}}.j2 dest=/etc/neutron/plugins/ml2/{{item}}
  with_items:
      - linuxbridge_agent.ini
  notify: restart neutron

- name: flush handlers in case of changed config
  meta: flush_handlers

- name: start neutron compute
  service: name={{ item }} state=started enabled=true
  with_items:
      - neutron-linuxbridge-agent
      - neutron-l3-agent

- name: wait for neutron to wake up
  pause: seconds=10
