
# Install required packages
- name: get the mitaka packages
  yum: pkg=centos-release-openstack-mitaka state=present update_cache=yes

- name: install packages
  yum: pkg={{item}} state=present
  with_items:
    - mariadb
    - mariadb-server
    - python2-PyMySQL

- name: configure mysql to run on all ports.
  copy: src=mysqld.cnf dest=/etc/my.cnf.d/mariadb-server.cnf
  notify: restart mariadb

- name: flush handlers in case of changed config
  meta: flush_handlers

- name: make sure mariadb is running
  service: name=mariadb state=started enabled=true
