
- name: restart nova
  service: name={{ item }} state=restarted
  with_items:
      - openstack-nova-api
      - openstack-nova-consoleauth
      - openstack-nova-scheduler
      - openstack-nova-conductor
      - openstack-nova-novncproxy
