- name: write sysctl files so quagga works correctly on hosts
  copy: src=99cumulus_defaults dest=/etc/sysctl.d/99cumulus_defaults.conf
  notify: reload sysctl files

- name: Install iproute for Quagga dependency
  yum: name=iproute update_cache=yes state=present

- name: download official quagga deb
  get_url: url=https://s3.amazonaws.com/cumulusfiles/roh-rhel7.tar validate_certs=False dest=/tmp/quagga.tar force=no

- name: Untar the package
  unarchive: src=/tmp/quagga.tar dest=/tmp/ copy=no

- name: Install Quagga
  yum: name=/tmp/rhel7/quagga-0.99.23.1+cl3u2-2016062001.el7.centos.x86_64.rpm

- name: copy Quagga daemons
  copy: src=daemons dest=/etc/quagga/
  notify: restart quagga

- name: copy Quagga conf
  template: src=Quagga.conf.j2 dest=/etc/quagga/Quagga.conf
  notify: restart quagga

- name: start quagga
  service: name=quagga state=started

- name: Force Interfaces Down
  command: ifdown {{item}}
  with_items:
    - lo:0
    - uplink1
    - uplink2

- name: Force Interfaces Up
  command: ifup {{item}}
  with_items:
    - lo:0
    - uplink1
    - uplink2
