
# Install required packages
- name: get the mitaka packages
  yum: pkg=centos-release-openstack-mitaka state=present update_cache=yes

- name: install packages
  yum: pkg={{item}} state=present update_cache=yes
  with_items:
    - openstack-dashboard
    - httpd


- name: horizon config files
  template: src={{item}}.j2 dest=/etc/openstack-dashboard/{{item}}
  with_items:
      - local_settings.py
  notify: restart apache2

- name: flush handlers in case of changed config
  meta: flush_handlers

- name: start apache
  service: name={{ item }} state=started enabled=true
  with_items:
      - httpd
