
# Install required packages
- name: get the mitaka packages
  yum: pkg=centos-release-openstack-mitaka state=present update_cache=yes

- name: install packages
  yum: pkg={{item}} state=present update_cache=yes
  with_items:
    - openstack-nova-compute
    - python-openstackclient

- name: nova config files
  template: src={{item}}.j2 dest=/etc/nova/{{item}}
  with_items:
      - nova.conf
      - nova-compute.conf
  notify: restart nova compute

- name: flush handlers in case of changed config
  meta: flush_handlers

- name: start nova compute
  service: name={{ item }} state=started enabled=true
  with_items:
      - openstack-nova-compute
      - libvirtd

- name: wait for nova to wake up
  pause: seconds=10
